name: build-push

on:
  push:
    tags:
      - v*

jobs:
  build-push:
    if: github.ref_type == 'tag'
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - id: setup
        run: |
          #!/bin/bash

          IMAGE="${GITHUB_REPOSITORY}"
          VERSION="${GITHUB_REF#refs/tags/v}"
          TAGS="${IMAGE}:${VERSION},${IMAGE}:latest"

          echo "TAGS=${TAGS}" >> $GITHUB_OUTPUT

      - name: actions/checkout
        uses: actions/checkout@v3

      - name: docker/setup-qemu-action
        uses: docker/setup-qemu-action@v2
        with:
          platforms: amd64,arm64

      - name: docker/setup-buildx-action
        uses: docker/setup-buildx-action@v2
        with:
          buildkitd-flags: --debug
          driver-opts: image=moby/buildkit:v0.10.5

      - name: docker/login-action
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          # ref: https://github.com/joehehir/servicestation/settings/secrets/actions

      - name: docker/build-push-action
        uses: docker/build-push-action@v3
        with:
          platforms: linux/amd64,linux/arm64
          context: ./src/
          tags: |
            ${{ steps.setup.outputs.TAGS }}
          push: true
